#!/bin/bash
#Copyright (c)  WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# WSO2 Inc. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# Please copy this file to /usr/local/bin and give executable permissions
# Sample usage : kubectl show api <api-name> -n=<namespace>
if [[ "$1" == "api" ]]
then

apiName=$2

echo -e "\nDetails of api "$apiName
kubectl describe api $2 $3

echo -e "\nSwagger used in the api "$apiName
kubectl describe configmap $2 $3

else
    echo "Unknown command"
fi

echo "Completed"