// Code generated by go-swagger; DO NOT EDIT.

// Package restserver Internal Utility API
//
//  This document specifies a **RESTful API** for allowing you to access internal data .
//  Please see [full swagger definition](https://raw.githubusercontent.com/wso2/carbon-apimgt/master/components/apimgt/org.wso2.carbon.apimgt.internal.service/src/main/resources/api.yaml) of the API which is written using [swagger 2.0](http://swagger.io/) specification.
//
//  Schemes:
//    https
//  Host: apis.wso2.com
//  BasePath: /operator/2.0
//  Version: 1.0.0
//  License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
//  Contact: WSO2<architecture@wso2.com> http://wso2.com/products/api-manager/
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/zip
//
// swagger:meta
package restserver
